version: '3'
services:
  spring-boot-app:
      build:
        context: ./jvm/backend.project
        dockerfile: Dockerfile
      ports:
        - "8080:8080"

  react-app:
      build:
        context: ./node/tfm-tc-frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - spring-boot-app